# Generated by Django 4.2.7 on 2023-12-12 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='Send to all')),
            ],
            options={
                'verbose_name': 'Email distribution',
                'verbose_name_plural': 'Email distributions',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('template', models.TextField(verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
            },
        ),
        migrations.CreateModel(
            name='UserEmailDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('email_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_distributions', to='mailganer.emaildistribution', verbose_name='Email distribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User email distribution',
                'verbose_name_plural': 'User email distributions',
            },
        ),
        migrations.AddField(
            model_name='emaildistribution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailganer.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emaildistribution',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='email_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
