# Generated by Django 4.2.7 on 2023-12-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailganer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremaildistribution',
            name='tracking_pixel_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tracking Pixel URL'),
        ),
    ]
